version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=development
      - DB_HOST=db
      - DB_NAME=sweet_delights
      - DB_USER=root
      - DB_PASS=secret
      - MAIL_HOST=10.101.1.114
      - MAIL_SMTPAuth=0
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_SMTPSECURE=
      - MAIL_PORT=1025
      - MAIL_FROM_ADDRESS=hello@sweet-delights.local
      - MAIL_FROM_NAME=Sweet Delights
      - APP_URL=http://10.101.1.114:8090
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8090:80"
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=sweet_delights
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
